# The different Materials to look for within the mine structure.
spawnPoint: SPONGE
mineCorner: POWERED_RAIL
sellNpc: WHITE_WOOL
upgradeMaterial: OBSIDIAN
quarryMaterial: SHULKER_BOX
mineDistance: 150
mineYLevel: 50
teleportDelay: 5
addWallGap: true
wallsGap: 1
shouldWallsGoUp: false
giveMineOnFirstJoin: true
preLoginGiveMine: true
onlyReplaceAir: true
borderUpgrade: true
locale: en_US
useAdventure: true
enableMenu: true
enableTax: true
sendTaxMessages: true
defaultClosed: true

mineTypes:
  Test:
    file: minewithgap.schem
    resetTime: 5
    expand: 1
    resetPercentage: 50.0
    upgradeCost: 1.0
    upgradeCurrency: VAULT # Supported currencies: VAULT, ULTRAPRISONCORE (Coming soon, hopefully...)
    useOraxen: true
    useItemsAdder: false
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    oraxen:
      orax_ore: 1.0
    itemsAdder:
      nice_stone: 1.0
    maxPlayers: 1
    flags:
      block-break: true
    fullFlags:
      block-place: false