name: PrivateMines
main: me.untouchedodin0.privatemines.PrivateMines
version: 5.3
api-version: 1.13

depend:
  - FastAsyncWorldEdit
  - WorldGuard
  - Vault

softdepend:
  - AutoSell
  - UltraPrisonCore
  - ProtocolLib
  - PlaceholderAPI
  - Oraxen
  - ItemsAdder