name: PrivateMines
main: me.untouchedodin0.privatemines.PrivateMines
version: 5.3.6
api-version: 1.13
authors:
  - UntouchedOdin0
  - BristerMitten
  - bobby29831
  - DrZoddiak
  - ComputerNerd100
  - bbSnavy
  - ClumsyIsNotReal

depend:
  - FastAsyncWorldEdit
  - WorldGuard
  - Vault

softdepend:
  - AutoSell
  - UltraPrisonCore
  - ProtocolLib
  - PlaceholderAPI
  - Oraxen
  - ItemsAdder